### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by limelect** [Fr0sT-Brutal/Delphi_OSMMap#14]
D10.2.3
Your older version compiled and worke but with mouse problems
so i wanted to check the newone

This is the error may be more?

[dcc32 Error] OSM.NetworkRequest.RTL.pas(128): E2010 Incompatible types: 'System.TArray<System.string>' and 'TStringDynArray'

Checking project dependencies...
Compiling OSMMapDemo.dproj (Debug, Win32)
brcc32 command line for "OSMMapDemo.vrc"
  c:\program files (x86)\embarcadero\studio\19.0\bin\cgrc.exe -c65001 "OSMMapDemo.vrc" -foOSMMapDemo.res 
dcc32 command line for "OSMMapDemo.dpr"
  c:\program files (x86)\embarcadero\studio\19.0\bin\dcc32.exe -$O- -$W+ --codepage:65001 -$R+ -$Q+ true --no-config -M -Q -TX.exe 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG -I"c:\program files (x86)\embarcadero\studio\19.0\lib\Win32\debug";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32\debug;..\3rdParty\Synapse;..\Source;
  "c:\program files (x86)\embarcadero\studio\19.0\lib\Win32\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakListView-2.3.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\VirtualTreeView-6.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakVirtualShell-2.7.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\PowerPDF-1.2;"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\DCU";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReport FMX Embarcadero 
  edition\LibD25";"C:\Program Files (x86)\Raize\CS5\Lib\RX10.2\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\RC6\Lib\RX10.2\Win32";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\EasyBMP-1.06;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\TFrameStand-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;
  C:\Users\Public\Documents\RTLPackages\FMXRTL\D10Tokyo\Win32\Release;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\AsyncPro-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\run;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\common;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\lib\d25\win32;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\packages\d25;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\alcinoe-master\source";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuard-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuardFMX-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\b\JEDIVisualComponentLibraryJVCL-3.51\resources;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\newac-master\src";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakCommonLibrary-2.3.0\Source;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\LimElec";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\unrxlib_275_u_1_0_18\units";C:\ADS;"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\LimElec\Win32\Debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\SynEdit-master\Source";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Gnostice_PDF\{code_GetSharedDir}\Lib\BDS2006";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\GLScene\lib\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\ImageEn v5.2.0 for D5-DX10.1 Berlin 
  Full Source\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\lib\win32\debug";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\DevExpress VCL 19.1.2 Full Source with DxAutoInstaller 2.2.2\DevExpressVCL19.1.2\Library\RS25";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win32";"g:\delphi 
  projects\expert\componentsearch\add comp to form\win32\debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastMM5-master";"C:\Program Files 
  (x86)\Embarcadero\Studio\FastMM4-master";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\TMS_Component_Pack_v9.2.4.0_Full_Source";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\ccpack\src";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win32";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecptt";"c:\program files 
  (x86)\embarcadero\studio\19.0\limlib\tvideograbber.10.6.2.2\dx10.2tokyo\win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecpt";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD Studio 10.2 Tokyo\Win32\Release" 
  -LEC:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl -LNC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp -NULib\Win32 -NSSystem.Win;Data.Win;
  Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap;Winapi; 
  -O..\3rdParty\Synapse;..\Source;"c:\program files (x86)\embarcadero\studio\19.0\lib\Win32\release";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files (x86)\embarcadero\studio\19.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakListView-2.3.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\VirtualTreeView-6.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakVirtualShell-2.7.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\PowerPDF-1.2;"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\DCU";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReport FMX Embarcadero 
  edition\LibD25";"C:\Program Files (x86)\Raize\CS5\Lib\RX10.2\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\RC6\Lib\RX10.2\Win32";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\EasyBMP-1.06;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\TFrameStand-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;
  C:\Users\Public\Documents\RTLPackages\FMXRTL\D10Tokyo\Win32\Release;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\AsyncPro-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\run;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\common;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\lib\d25\win32;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\packages\d25;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\alcinoe-master\source";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuard-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuardFMX-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\b\JEDIVisualComponentLibraryJVCL-3.51\resources;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\newac-master\src";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakCommonLibrary-2.3.0\Source;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\LimElec";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\unrxlib_275_u_1_0_18\units";C:\ADS;"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\LimElec\Win32\Debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\SynEdit-master\Source";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Gnostice_PDF\{code_GetSharedDir}\Lib\BDS2006";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\GLScene\lib\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\ImageEn v5.2.0 for D5-DX10.1 Berlin 
  Full Source\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\lib\win32\debug";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\DevExpress VCL 19.1.2 Full Source with DxAutoInstaller 2.2.2\DevExpressVCL19.1.2\Library\RS25";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win32";"g:\delphi 
  projects\expert\componentsearch\add comp to form\win32\debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastMM5-master";"C:\Program Files 
  (x86)\Embarcadero\Studio\FastMM4-master";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\TMS_Component_Pack_v9.2.4.0_Full_Source";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\ccpack\src";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win32";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecptt";"c:\program files 
  (x86)\embarcadero\studio\19.0\limlib\tvideograbber.10.6.2.2\dx10.2tokyo\win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecpt";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD Studio 10.2 Tokyo\Win32\Release" -R..\3rdParty\Synapse;..\Source;"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win32\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakListView-2.3.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\VirtualTreeView-6.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakVirtualShell-2.7.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\PowerPDF-1.2;"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\DCU";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReport FMX Embarcadero 
  edition\LibD25";"C:\Program Files (x86)\Raize\CS5\Lib\RX10.2\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\RC6\Lib\RX10.2\Win32";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\EasyBMP-1.06;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\TFrameStand-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;
  C:\Users\Public\Documents\RTLPackages\FMXRTL\D10Tokyo\Win32\Release;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\AsyncPro-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\run;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\common;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\lib\d25\win32;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\packages\d25;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\alcinoe-master\source";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuard-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuardFMX-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\b\JEDIVisualComponentLibraryJVCL-3.51\resources;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\newac-master\src";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakCommonLibrary-2.3.0\Source;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\LimElec";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\unrxlib_275_u_1_0_18\units";C:\ADS;"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\LimElec\Win32\Debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\SynEdit-master\Source";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Gnostice_PDF\{code_GetSharedDir}\Lib\BDS2006";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\GLScene\lib\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\ImageEn v5.2.0 for D5-DX10.1 Berlin 
  Full Source\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\lib\win32\debug";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\DevExpress VCL 19.1.2 Full Source with DxAutoInstaller 2.2.2\DevExpressVCL19.1.2\Library\RS25";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win32";"g:\delphi 
  projects\expert\componentsearch\add comp to form\win32\debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastMM5-master";"C:\Program Files 
  (x86)\Embarcadero\Studio\FastMM4-master";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\TMS_Component_Pack_v9.2.4.0_Full_Source";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\ccpack\src";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win32";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecptt";"c:\program files 
  (x86)\embarcadero\studio\19.0\limlib\tvideograbber.10.6.2.2\dx10.2tokyo\win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecpt";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD Studio 10.2 Tokyo\Win32\Release" -U"c:\program files 
  (x86)\embarcadero\studio\19.0\lib\Win32\debug";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32\debug;..\3rdParty\Synapse;..\Source;
  "c:\program files (x86)\embarcadero\studio\19.0\lib\Win32\release";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\19.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp;"c:\program files (x86)\embarcadero\studio\19.0\include";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakListView-2.3.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\VirtualTreeView-6.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakVirtualShell-2.7.0\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\PowerPDF-1.2;"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\DCU";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastReport FMX Embarcadero 
  edition\LibD25";"C:\Program Files (x86)\Raize\CS5\Lib\RX10.2\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\RC6\Lib\RX10.2\Win32";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\EasyBMP-1.06;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\TFrameStand-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;
  C:\Users\Public\Documents\RTLPackages\FMXRTL\D10Tokyo\Win32\Release;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\AsyncPro-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\run;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\common;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\lib\d25\win32;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDIVisualComponentLibraryJVCL-3.5\packages\d25;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\JEDICodeLibraryJCL-3.0\lib\d25\win32;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\alcinoe-master\source";C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuard-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\OnGuardFMX-1.3\source;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\b\JEDIVisualComponentLibraryJVCL-3.51\resources;
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\RibbonFramework-1.2.1\Lib;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\newac-master\src";
  C:\Users\LimElect\Documents\Embarcadero\Studio\19.0\CatalogRepository\MustangpeakCommonLibrary-2.3.0\Source;"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\LimElec";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\unrxlib_275_u_1_0_18\units";C:\ADS;"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\LimElec\Win32\Debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\SynEdit-master\Source";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Gnostice_PDF\{code_GetSharedDir}\Lib\BDS2006";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\GLScene\lib\Win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\ImageEn v5.2.0 for D5-DX10.1 Berlin 
  Full Source\Source";"C:\Program Files (x86)\Embarcadero\Studio\19.0\lib\win32\debug";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\DevExpress VCL 19.1.2 Full Source with DxAutoInstaller 2.2.2\DevExpressVCL19.1.2\Library\RS25";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\FastReports\LibD25";"C:\Program Files (x86)\Raize\RadiantShapes\Lib\RX10.2\Win32";"g:\delphi 
  projects\expert\componentsearch\add comp to form\win32\debug";"C:\Program Files (x86)\Embarcadero\Studio\19.0\FastMM5-master";"C:\Program Files 
  (x86)\Embarcadero\Studio\FastMM4-master";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\TMS_Component_Pack_v9.2.4.0_Full_Source";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\ccpack\src";"C:\Users\LimElect\Documents\Gnostice\Document Studio Delphi\Lib\RAD10.2\Win32";"C:\Program 
  Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecptt";"c:\program files 
  (x86)\embarcadero\studio\19.0\limlib\tvideograbber.10.6.2.2\dx10.2tokyo\win32";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\madExecpt";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX";"C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL";
  "C:\Program Files (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\FMX\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Source\VCL\Designtime";"C:\Program Files 
  (x86)\Embarcadero\Studio\19.0\LimLib\Skia4Delphi\Library\RAD Studio 10.2 Tokyo\Win32\Release" -V -VN -K00400000 
  -NBC:\Users\Public\Documents\Embarcadero\Studio\19.0\Dcp -NHC:\Users\Public\Documents\Embarcadero\Studio\19.0\hpp\Win32 -NOLib\Win32   OSMMapDemo.dpr 
    
[dcc32 Error] OSM.NetworkRequest.RTL.pas(128): E2010 Incompatible types: 'System.TArray<System.string>' and 'TStringDynArray'
[dcc32 Fatal Error] MainUnit.pas(32): F2063 Could not compile used unit 'OSM.NetworkRequest.RTL.pas'
Failed
Elapsed time: 00:00:00.8

**Comment by limelect** [comment]
Fixed by adding System.Types and changing  HdrArr:TStringDynArray;// TArray<string>;

**Comment by Fr0sT-Brutal** [comment]
Thanks for pointing this out, I committed your fix. Very odd selection of result type...
