### ISSUE TITLE
Draw polygon

### ISSUE THREAD

**Issue by soinalastudio** [Fr0sT-Brutal/Delphi_OSMMap#18]
Hello, thank you for your component. How to Draw Polygons on the map please? 
Thank you

**Comment by Express2000** [comment]
I have the same question. Hope it's planned to be implemented.

**Comment by Fr0sT-Brutal** [comment]
Currently you can do it with tracks feature implemented in c64175261fab18b7525b7edc76174dbf30e1ea89. Plz tell if that's enough for your purposes. Closing the issue for now
