### ISSUE TITLE
Polygone area

### ISSUE THREAD

**Issue by ClubACNews** [Fr0sT-Brutal/Delphi_OSMMap#20]
Good morning,
I am part of a team of archaeologists in France who carry out diagnostics or excavations on sites before development.
I created software under Lazarus archiving our activity with an SQLite database.
I'm trying to create a free application so that other archaeological cells can also use it.
Your component interests me because OSM does not require API code to view the maps.
In the context of my application, your components are incomplete. In order to visualize the areas diagnosed or searched, I would like to be able to delimit each area by a closed polygon.
Is this functionality planned? If positive, is there an end date for completion?
Looking forward to your feedback because this feature is eagerly awaited on my side and I would like to serve as a tester for the development.
Good day.
F. PARTY

**Comment by Fr0sT-Brutal** [comment]
Hi!
Currently the request is pretty achievable with addition of tracks (you can add polygon of any form by coordinates). Line style, width and color could be customized. The only feature that couldn't be reached is filling of that polygon

**Comment by Fr0sT-Brutal** [comment]
With the new version you can draw anything you want in view area, check demo drawing a square.
Closing as done. Feel free to comment/reopen if any issues happen

**Comment by ClubACNews** [comment]
Hi,
With Lazarus 2.2.6, the install of OSMmap make an error in osm.TilesProvider file with the "TReplTokenCallback = reference to function(var Token: string): Boolean;  "
He don't know  "reference".
Thanks

**Comment by Fr0sT-Brutal** [comment]
The feature requires modern FPC (IDK exact version), see https://forum.lazarus.freepascal.org/index.php?topic=59468.0
