### ISSUE TITLE
OSMMap and Lazarus 3.00

### ISSUE THREAD

**Issue by ClubACNews** [Fr0sT-Brutal/Delphi_OSMMap#26]
Hi, 
I have installed Lazarus 3.O with Fpcupdeluxe and I have the same error with "reference" in line 254 on the OSM.TilesProvider Unit.
You have said the the problem was not present with the release 3.00.
How use your package ?
Thanks
François

**Comment by Fr0sT-Brutal** [comment]
Hi, I haven't said " the problem was not present with the release 3.00". I've said that references were added to language somewhere in the mid'22. IDK when the release with this feature will come out but you can use current source base and build it locally. fpcupdeluxe makes the process easy.
BTW, it's the FPC that you must upgrade, Lazarus is not related to this feature

**Comment by ClubACNews** [comment]
Hi,What release level should I select for FPC and Lazarus in fpcupdeluxe for use your source in Windows 10 64 Bits?ThanksFrançois


Je pense ENVIRONNEMENT: ai-je vraiment besoin d'imprimer ce message ? 
Please consider the environment before printing this email. 

    Le vendredi 29 décembre 2023 à 09:16:18 UTC+1, Fr0sT-Brutal ***@***.***> a écrit :  
 
 


Hi, I haven't said " the problem was not present with the release 3.00". I've said that references were added to language somewhere in the mid'22. IDK when the release with this feature will come out but you can use current source base and build it locally. fpcupdeluxe makes the process easy

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Sans virus.www.avast.com |

**Comment by ClubACNews** [comment]
Hi,
I close it because i've made a new directory with the last release of fpcupdeluxe 2.4.0c with FPC and Lazarus in Trunk.
Now, i can start the demo in Lazarus.
I continue my dev with to try polygone with funtion tracks.
Thanks
