### ISSUE TITLE
Tile not saved

### ISSUE THREAD

**Issue by array81** [Fr0sT-Brutal/Delphi_OSMMap#4]
I have problem to run demo on Delphi XE2. The demo get error about PNG not valid it would seem te PNG is download but not saved. In TNetworkRequestThread.Execute I think the stream is not transferred, so a black stream is saved. Right?

**Comment by AlexHausauer** [comment]
У меня тоже была такая проблема, когда некоторые части загружались с ошибкой. Так как в программе нет обработки ошибок на загрузку и сохранение png файла, иногда сервер из-за ошибки подключения в поток помещал не содержимое  закачиваемого файла, а текстовую информацию об ошибке на сервере. И тогда программа, открывая такой загруженный файл (по сути файл html), не смогла преобразовать его в png. Что бы избавиться от ошибки нужно удалить все файлы, которые уже были закешированы на диске и повторить попытку с повторной загрузкой карт, убедившись что есть доступ к сети интернет и прокси не блокирует подключение.

**Comment by Fr0sT-Brutal** [comment]
@array81 yeah probably @AlexHausauer is right (server returned non-PNG response). I'll look into adding error check for received responses

**Comment by array81** [comment]
The problem is the agent. OSM does not return tile if the connection does not have agent.

**Comment by Fr0sT-Brutal** [comment]
@array81, you're right, that was the problem! I'm now currently working on this issue, had to rework almost all netrequest internals. As a side improvement, proxy and auth support are added.

**Comment by Fr0sT-Brutal** [comment]
Now, with the new v.0.5.0, this issue is fixed
