### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JakubKrawczuk** [Fr0sT-Brutal/Delphi_OSMMap#7]
Could you add license to this repository? I would like to use this library in commercial project and i am not sure if i can.

**Comment by Fr0sT-Brutal** [comment]
Licensed as MPL - I believe this allows any kind of usage, but modifications of the lib itself should be made public. Plz tell if these conditions fit your needs.

**Comment by JakubKrawczuk** [comment]
I belive this license requires my company to publish changes made in library and i'm ok with that. Just need to ask my superior if we have a way to do this (like company github account or something)

**Comment by Fr0sT-Brutal** [comment]
AFAIU (I'm not a jurist and you better consult with pro's) with the OSS license your company is only required to give these modified sources to anyone who requests them but not obliged to do it via public servers (private email to those who ask is OK). Anyway with MPL this only applies if you make modifications to the units themselves (thus helping to improve the lib) - descendant classes are not affected.

**Comment by JakubKrawczuk** [comment]
Thank you
